### ISSUE TITLE
memory problem when trying to compile libmbd

### ISSUE THREAD

**Issue by awvwgk** [jhrmnn/libmbd#13]
I tried compiling `libmbd` on my local machine but failed at

```
> mkdir build && cd build
> cmake ..
-- The Fortran compiler identification is GNU 9.2.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Setting build type to Debug as none was set
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /usr/lib/libopenblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - not found
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awvwgk/src/libmbd/build
> make
Scanning dependencies of target mbd
```

with my machine *crashing*. For some reasons `cmake` was using the entire available memory of my machine and started filling up the swap until the machine finally crashed. With swap the machine has 16 GB of memory available and was only running make to build `libmbd`.

I retried on a machine with 64 GB of memory and got the same behaviour. The setup on both of my machines is

- Manjaro Linux 18.1.1-rc2
- `cmake` 3.15.2
- `make` 4.2.1

Eventually I got it compiled on a cluster node with 256 GB of memory, which is kind of unsatisfactory for development. The setup of the node is

- openSuse Leap 15.1
- `cmake` 3.10.2
- `make` 4.2.1

The difference in the two environments are the `cmake` versions and the OS, not sure if it is a `cmake` problem. I would expect the build system to be less memory consuming.

Any ideas here?

**Comment by jhrmnn** [comment]
First, this really shouldn't happen. Second, the Cmake script of Libmbd is pretty standard, so I find it very unlikely that the behavior you observe would be specific to Libmbd. How much memory does Cmake use on the cluster node?

**Comment by awvwgk** [comment]
I guess so, yet it happened. The build on the cluster node runs fine without using much memory, as it should. Most probably this is a `cmake` related problem on my system, but `libmbd` is the only Fortran project where this occurred so far.

I should try it on another system or downgrade my `cmake` version to be sure.

**Comment by jhrmnn** [comment]
I've compiled Libmbd with Cmake 3.14.x and 3.15.x without any issues so far, both on Linux and macOS. I'd be happy to help, but this seems very system specific. Let me know if you figure out the source of the memory problem.

**Comment by jhrmnn** [comment]
Have you had any luck figuring out the source of the issue?

**Comment by awvwgk** [comment]
Not really, I circumvented the issue by not using `libmbd` for now. It worked by creating a VM with a openSuse image and compiling it there, but this turned out to be rather inconvenient.

Sorry for bothering you with this issue. I will close it since it seems very system specific.
