### ISSUE TITLE
libmbd doesn't compile with IBM XL Fortran compiler

### ISSUE THREAD

**Issue by vyu16** [jhrmnn/libmbd#16]
After [this commit](https://github.com/jhrmnn/libmbd/commit/d7f0ae14d92a2c7912ad6b6a13b921f37e1d9951), libmbd no longer compiles with IBM XL Fortran compiler (version 16.1.1-x). An ICE was triggered during the compilation of `mbd_matrix.F90` and `mbd_dipole.F90`.

This commit replaces `forall` by `do concurrent`. Looks like XL Fortran crashes if `do concurrent` is used within an `associate` block. I'm 99% sure this is a bug of the compiler, which is out of our control. I've verified that the code compiles fine after removing the `associate`, or switching to a bare `do`, or reverting back to `forall`.

@jhrmnn Up to you to decide whether/how to support IBM compilers.

**Comment by jhrmnn** [comment]
Thanks for figuring this out! I have no problem fixing this for the moment. Can you please verify if the branch `fix-ibm-fortran` fixes the issue?

Is this a current version of the IBM compiler? If not, do you have access to more recent versions? If so, is there a way to file a bug report?

**Comment by vyu16** [comment]
Yes, the `fix-ibm-fortran` branch works. I'm testing with two versions: current default on Summit 16.1.1-5, and the latest version 16.1.1-8. I believe there must be a way to report a bug, but I couldn't find it 😅

**Comment by jhrmnn** [comment]
Thanks!

Well, someone has to pay for the compiler, and they should be able to complain to someone that the thing they bought doesn't work as expected :)

**Comment by linda-chui** [comment]
hi @vyu16 , firstly a disclaimer - i work for IBM and in the compiler area. Our understanding is that SUMMIT (or more accurately, ORNL) has a mechanism to support their users, including opening support cases (in this case, with IBM) on their behalf.   We're interested in learning about this issue so would appreciate if you could take a moment to contact ORNL or whoever arranged your access to SUMMIT to file a report?  Thanks in advance!

**Comment by vyu16** [comment]
Hey @linda-chui , thanks for the info. Very good to know! I'll try creating a mini reproducer and file a bug report to OLCF.

**Comment by vyu16** [comment]
@jhrmnn FYI, `do concurrent` + `associate` is now working with IBM XL Fortran 16.1.1-10.

**Comment by jhrmnn** [comment]
Thanks! Though I guess it's going to take some time before I can safely revert the patch.
