### ISSUE TITLE
Global module variables

### ISSUE THREAD

**Issue by aradi** [jhrmnn/libmbd#22]
We are in the process of eliminating all non-constant module variables in DFTB+ (see PR [678 ](https://github.com/dftbplus/dftbplus/pull/678)) in order to allow concurrent DFTB+ calculators when using it as a library.

During the review I've realized, that also libMBD uses a few module variable, for example in mbd_coulomb.f90. It would be nice, if libMBD could be made completely module variable free as well, so that we could include it in the library build even if the user asks for a version supporting multiple DFTB+ instances.

**Comment by jhrmnn** [comment]
Sure. Please let me know if I missed something. `mbd_coulomb` isn't accessible from the Fortran API anyway, so ti could have not been used in DFTB+, but now there shouldn't be any module-level variables in the whole codebase.
